packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies: []

peerDependencyRules:
  allowedVersions:
    "@0gfoundation/0g-storage-ts-sdk>ethers": "6.17.0"

overrides:
  "open-jsonrpc-provider>axios": "1.19.0"
  "@ethersproject/providers>ws": "8.21.0"
  "@0gfoundation/0g-compute-ts-sdk>adm-zip": "0.6.0"
