[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
cbor_metadata = false
remappings = ["forge-std/=lib/forge-std/src/"]

[profile.default.fuzz]
runs = 512

[profile.default.invariant]
runs = 128
depth = 32
fail_on_revert = true

[rpc_endpoints]
og_mainnet = "${OG_MAINNET_RPC_URL}"
og_galileo = "${OG_GALILEO_RPC_URL}"
local = "${ANVIL_RPC_URL}"
